package com.ongmanager.exception;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    TOKEN_INVALID,
    RESOURCE_NOT_FOUND,
    DUPLICATE_ENTRY,
    VALIDATION_ERROR,
    INSUFFICIENT_PERMISSIONS,
    ONG_NOT_APPROVED,
    EMAIL_NOT_VERIFIED,
    INTERNAL_ERROR
}
